bakery_accounting/urls.py
from django.urls import path
from . import views

app_name = 'bakery_accounting'

urlpatterns = [
    path('', views.bakerysales_view, name='bakerysales'),
    path('bakery-sales-upload/', views.bakery_sales_upload, name='bakery-sales-upload'),
    path('add-bakery-sales/', views.add_bakery_sales.as_view(), name='add-bakery-sales'),
    path('edit-bakery-sales/<int:pk>/', views.edit_bakery_sales.as_view(), name='edit-bakery-sales'),

    path('bakerypayments', views.bakery_payments_view, name='bakerypayments'),
    path('bakery-payments-upload/', views.bakery_payments_upload, name='bakery-payments-upload'),
    path('add-bakery-payments/', views.add_bakery_payments.as_view(), name='add-bakery-payments'),
    path('edit-bakery-payments/<int:pk>/', views.edit_bakery_payments.as_view(), name='edit-bakery-payments'),

    path('bakeryreturns', views.bakery_returns_view, name='bakeryreturns'),
    path('bakery-returns-upload/', views.bakery_returns_upload, name='bakery-returns-upload'),
    path('add-bakery-returns/', views.add_bakery_returns.as_view(), name='add-bakery-returns'),
    path('edit-bakery-returns/<int:pk>/', views.edit_bakery_returns.as_view(), name='edit-bakery-returns'),

    path('bakery-opening-bal', views.bakery_opening_bal_view, name='bakery-opening-bal'),
    path('bakery-opening-bal-upload/', views.bakery_opening_bal_upload, name='bakery-opening-bal-upload'),
    path('add-bakery-opening-bal/', views.add_bakery_opening_bal.as_view(), name='add-bakery-opening-bal'),
    #path('edit-bakery-returns/<int:pk>/', views.edit_bakery_returns.as_view(), name='edit-bakery-returns'),

    path('bakery-inventory', views.bakery_inventory_view, name='bakery-inventory'),
    #path('bakery-opening-bal-upload/', views.bakery_opening_bal_upload, name='bakery-opening-bal-upload'),
    path('add-bakery-inventory/', views.add_bakery_inventory.as_view(), name='add-bakery-inventory'),
    path('edit-bakery-inventory/<int:pk>/', views.edit_bakery_inventory.as_view(), name='edit-bakery-inventory'),


    path('bakerypurchases', views.bakery_purchases_view, name='bakerypurchases'),
    path('add-bakery-purchase/', views.add_bakery_purchase.as_view(), name='add-bakery-purchase'),
    path('edit-bakery-purchase/<int:pk>/', views.edit_bakery_purchase.as_view(), name='edit-bakery-purchase'),

    path('bakery-rm-damages', views.bakery_rm_damages_view, name='bakery-rm-damages'),
    path('add-bakery-rm-damage/', views.add_bakery_rm_damages.as_view(), name='add-bakery-rm-damage'),
    path('edit-bakery-rm-damage/<int:pk>/', views.edit_bakery_rm_damages.as_view(), name='edit-bakery-rm-damage'),

]

bank/urls.py
from django.urls import path
from . import views

app_name = 'bank'

urlpatterns = [
    path('', views.bank_view, name='bank'),
    path('bank-transactions', views.bank_transactions, name='bank-transactions'),
    path('account-detail/<slug:slug>/',views.bank_account_details, name='account-detail'),
    path('add-deposit/', views.add_deposit.as_view(), name='add-deposit'),
    path('add-withdrawal/', views.add_withdrawal.as_view(), name='add-withdrawal'),
    path('account-opening_bal/', views.add_account_opening_bal.as_view(), name='account-opening-bal'),
    path('add-bank-charges/', views.add_bank_charges.as_view(), name='add-bank-charges'),
    path('edit-deposit/<int:pk>/', views.edit_deposit.as_view(), name='edit-deposit'),
    path('edit-withdrawal/<int:pk>/', views.edit_withdrawal.as_view(), name='edit-withdrawal'),
    path('edit-account-opening-bal/<int:pk>/', views.edit_account_opening_bal.as_view(), name='edit-account-opening-bal'),



    #path('worker-detail/<slug:slug>/',views.worker_detail, name='worker-detail'),

    #path('add-department/', views.add_department.as_view(), name='add-department'),
    #path('add-role/', views.add_role.as_view(), name='add-role'),
    #path('edit-worker/<int:pk>/', views.edit_worker.as_view(), name='edit-worker'),
    #path('delete-worker/<int:pk>/', views.delete_worker.as_view(), name='delete-worker'),



]

bjcomplexerp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('configurations/', include('configurations.urls', namespace='configurations')),
    path('task/', include('task.urls', namespace='task')),
    path('purchase/', include('purchase.urls', namespace='purchase')),
    #path('bakerycustomersinvoices/', include('bakerycustomersinvoices.urls', namespace='bakerycustomersinvoices')),
    path('bank/', include('bank.urls', namespace='bank')),
    path('bakery_accounting/', include('bakery_accounting.urls', namespace='bakery_accounting')),
    path('general_ledger/', include('general_ledger.urls', namespace='general_ledger')),
    path('procurement/', include('procurement.urls', namespace='procurement')),
    path('contact_list/', include('contact_list.urls', namespace='contact_list')),
    #path('employee/', include('employee.urls', namespace='employee')),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

procurement/urls.py
from django.urls import path
from . import views

app_name = 'procurement'

urlpatterns = [
    #path('', views.task_home, name='task-home'),
    #path('add-task/', views.add_task.as_view(), name='add-task'),
    #path('task-detail/<slug:slug>/',views.task_detail, name='task-detail'),
    #path('edit-task/<int:pk>/', views.edit_task.as_view(), name='edit-task'),

]

procurement/models.py
from __future__ import unicode_literals
from django.db import models

from decimal import Decimal
from django.urls import reverse
from django.core.validators import RegexValidator, MinValueValidator
import uuid

import datetime
from django.utils.timezone import now
from django.template.defaultfilters import slugify

from django.db.models.signals import post_save
from configurations.models import *

from django.db.models import Sum
from django.conf import settings
from django.urls import reverse
from django.dispatch import receiver
# phone validator using regular expressions
phone_regex = RegexValidator(
    regex=r'^\+?1?\d{9,15}$',
    message='Phone number invalid. Should start with example: +237'
)



# --------------- INVOICE NUMBER GENERATOR FOR Purhcases------------ #
def increment_invoice_number():
    last_invoice = Purchase.objects.all().order_by('id').last()
    today = datetime.date.today()
    today_string = today.strftime("%Y-%m-%d")

    if not last_invoice:
            return today_string + "-" + 'INV0001'

    invoice_id = last_invoice.invoice_id
    invoice_int = int(invoice_id.split('INV000')[-1])
    new_invoice_int = invoice_int + 1

    new_invoice_id = today_string + "-" + 'INV000'  + str(new_invoice_int)
    return new_invoice_id

class Procurement(models.Model):
    DEPARTMENTS = (
        ('Bakery', 'Bakery'),
        ('Boulangerie', 'Boulangerie'),
        ('Supermarket', 'Supermarket'),
        ('Bar', 'Bar'),
        ('Snack', 'Snack'),
        ('Ice Cream', 'Ice Cream'),

    )
    created_at = models.DateField(default=now)
    department =  models.CharField(max_length = 500, choices=DEPARTMENTS, default='', null = True, blank = True, verbose_name = 'Department')
    procurement_manager = models.CharField(max_length = 500, null = True, blank = True, verbose_name = "Procurement Manager")
    vendor = models.CharField(max_length = 500, null = True, blank = True)
    description = models.CharField(max_length = 500, null = True, blank = True)
    slug = models.SlugField(max_length=100, unique=True, blank=True, default=uuid.uuid4)
    invoice_id = models.CharField(max_length = 500, null = True, blank = True)
    stock_dept_invoice_id = models.CharField(max_length=200, null = True, blank = True, verbose_name = "Stock Dept Invoice Id")

    amount = models.DecimalField(max_digits=20, decimal_places=2, default=0)
    due_date = models.DateField(default=now)

    def __str__(self):
        return self.department

    #def get_absolute_url(self):
        #return reverse('purchase:purchase-details', args=[self.slug])

    def save(self, *args, **kwargs):
            self.slug = slugify(self.vendor)
            super(Procurement, self).save(*args, **kwargs)

    class Meta:
        ordering = ['-created_at']
        verbose_name = 'Procurement'
        verbose_name_plural = 'Procurement'

templates/procurement/forms/add_procurement.html
{% extends "base2.html" %}
{% load static %}
{% load widget_tweaks %}

{% block css %}
    <link rel="stylesheet" href="{% static '' %}bootstrap-datetimepicker.min.css">
    <link rel="stylesheet" type="text/css" href="{% static '' %}lib/pickadate.css">
 {% endblock %}

{% block title %} Add Inventory{% endblock title %}

{% block content %}

<div class="content-body">
    <!-- Basic form layout section start -->
    <section id="basic-form-layouts">
        <div class="row match-height">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title" id="basic-layout-form">Bakery Inventory Form</h3>
                        <a class="heading-elements-toggle"><i class="la la-ellipsis-v font-medium-3"></i></a>
                        <div class="heading-elements">
                            <ul class="list-inline mb-0">
                                <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                                <li><a data-action="reload"><i class="ft-rotate-cw"></i></a></li>
                                <li><a data-action="expand"><i class="ft-maximize"></i></a></li>
                                <li><a data-action="close"><i class="ft-x"></i></a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="card-content collapse show">
                        <div class="card-body">
                            <div class="card-text">
                                <p></p>
                            </div>

                            <form class="form" method="post" novalidate>
                              {% csrf_token %}

                              <div class="row">
                                  <div class="col-md-3">
                                      <div class="form-group">
                                          <label for="projectinput1">Date</label>
                                          {% render_field form.created_at class="form-control" placeholder="Date" %}
                                      </div>
                                  </div>

                                  <div class="col-md-3">
                                    <div class="form-group">
                                        <label for="projectinput1">Department</label>
                                        {% render_field form.department class="form-control" placeholder="" %}
                                    </div>
                                  </div>

                                  <div class="col-md-3">
                                    <div class="form-group">
                                        <label for="projectinput1">Procuement Manager</label>
                                        {% render_field form.procuement_manager class="form-control" placeholder="" %}
                                    </div>
                                  </div>


                              </div>

                              <div class="row">

                                <div class="col-md-3">
                                  <div class="form-group">
                                      <label for="projectinput1">Purchase Id</label>
                                      {% render_field form.purchase_id class="form-control" placeholder="" %}
                                  </div>
                                </div>

                                <div class="col-md-3">
                                  <div class="form-group">
                                      <label for="projectinput1">Supplier</label>
                                      {% render_field form.supplier class="form-control" placeholder="" %}
                                  </div>
                                </div>

                                  <div class="col-md-3">
                                      <div class="form-group">
                                          <label for="projectinput1">Category</label>
                                          {% render_field form.category class="form-control" placeholder="Address" rows="2" %}
                                      </div>
                                  </div>

                                  <div class="col-md-3">
                                    <div class="form-group">
                                        <label for="projectinput1">Entry Measure</label>
                                        {% render_field form.entry_measure class="form-control" placeholder="" %}
                                    </div>
                                  </div>


                            </div>

                              <div class="row">

                                <div class="col-md-3">
                                  <div class="form-group">
                                      <label for="projectinput1">Weight / Pack</label>
                                      {% render_field form.weight_pack class="form-control" placeholder="" %}
                                  </div>
                                </div>

                                  <div class="col-md-3">
                                      <div class="form-group">
                                          <label for="projectinput1">Product</label>
                                          {% render_field form.product class="form-control" placeholder="Product Name" %}
                                      </div>
                                  </div>

                                  <div class="col-md-3">
                                      <div class="form-group">
                                          <label for="projectinput1">Qty</label>
                                          {% render_field form.qty class="form-control" placeholder="0" %}
                                      </div>
                                  </div>

                                  <div class="col-md-3">
                                      <div class="form-group">
                                          <label for="projectinput1">Unit Cost Price</label>
                                          {% render_field form.unit_cost_price class="form-control" placeholder="0" %}
                                      </div>
                                  </div>



                                  <div class="col-md-3">
                                      <div class="form-group">
                                          <label for="projectinput1">Total Amount (Calculated Field)</label>
                                          {% render_field form.total_cost_price class="form-control" placeholder="0" %}
                                      </div>
                                  </div>

                              </div>

                                  <div class="form-actions">
                                      <a href="{% url 'bakery_accounting:bakerypurchases' %}">
                                      <button type="button" class="btn btn-warning mr-1">
                                          <i class="ft-x"></i> Cancel
                                      </button>
                                    </a>
                                      <button type="submit" class="btn btn-primary">
                                          <i class="la la-check-square-o"></i> Save
                                      </button>
                                  </div>


                            </form>

                        </div>
                    </div>
                </div>
            </div>








    </section>
    <!-- // Basic form layout section end -->
</div>

{% endblock content %}
  <script src="{% static '' %}lib/picker.js"></script>
  <script src="{% static '' %}lib/picker.date.js"></script>
  <script src="{% static '' %}lib/legacy.js"></script>

  <script type="text/javascript">
      $("#id_due_date").pickadate({format: 'yyyy-mm-dd' }).val();
</script>

{% block script %}

 {% endblock %}