bakery_accounting/urls.py
from django.urls import path
from . import views

app_name = 'bakery_accounting'

urlpatterns = [
    path('', views.bakerysales_view, name='bakerysales'),
    path('bakery-sales-upload/', views.bakery_sales_upload, name='bakery-sales-upload'),
    path('add-bakery-sales/', views.add_bakery_sales.as_view(), name='add-bakery-sales'),
    path('edit-bakery-sales/<int:pk>/', views.edit_bakery_sales.as_view(), name='edit-bakery-sales'),

    path('bakerypayments', views.bakery_payments_view, name='bakerypayments'),
    path('bakery-payments-upload/', views.bakery_payments_upload, name='bakery-payments-upload'),
    path('add-bakery-payments/', views.add_bakery_payments.as_view(), name='add-bakery-payments'),
    path('edit-bakery-payments/<int:pk>/', views.edit_bakery_payments.as_view(), name='edit-bakery-payments'),

    path('bakeryreturns', views.bakery_returns_view, name='bakeryreturns'),
    path('bakery-returns-upload/', views.bakery_returns_upload, name='bakery-returns-upload'),
    path('add-bakery-returns/', views.add_bakery_returns.as_view(), name='add-bakery-returns'),
    path('edit-bakery-returns/<int:pk>/', views.edit_bakery_returns.as_view(), name='edit-bakery-returns'),

    path('bakery-opening-bal', views.bakery_opening_bal_view, name='bakery-opening-bal'),
    path('bakery-opening-bal-upload/', views.bakery_opening_bal_upload, name='bakery-opening-bal-upload'),
    path('add-bakery-opening-bal/', views.add_bakery_opening_bal.as_view(), name='add-bakery-opening-bal'),
    #path('edit-bakery-returns/<int:pk>/', views.edit_bakery_returns.as_view(), name='edit-bakery-returns'),

    path('bakery-inventory', views.bakery_inventory_view, name='bakery-inventory'),
    #path('bakery-opening-bal-upload/', views.bakery_opening_bal_upload, name='bakery-opening-bal-upload'),
    path('add-bakery-inventory/', views.add_bakery_inventory.as_view(), name='add-bakery-inventory'),
    path('edit-bakery-inventory/<int:pk>/', views.edit_bakery_inventory.as_view(), name='edit-bakery-inventory'),


    path('bakerypurchases', views.bakery_purchases_view, name='bakerypurchases'),
    path('add-bakery-purchase/', views.add_bakery_purchase.as_view(), name='add-bakery-purchase'),
    path('edit-bakery-purchase/<int:pk>/', views.edit_bakery_purchase.as_view(), name='edit-bakery-purchase'),

    path('bakery-rm-damages', views.bakery_rm_damages_view, name='bakery-rm-damages'),
    path('add-bakery-rm-damage/', views.add_bakery_rm_damages.as_view(), name='add-bakery-rm-damage'),
    path('edit-bakery-rm-damage/<int:pk>/', views.edit_bakery_rm_damages.as_view(), name='edit-bakery-rm-damage'),

]

bank/urls.py
from django.urls import path
from . import views

app_name = 'bank'

urlpatterns = [
    path('', views.bank_view, name='bank'),
    path('bank-transactions', views.bank_transactions, name='bank-transactions'),
    path('account-detail/<slug:slug>/',views.bank_account_details, name='account-detail'),
    path('add-deposit/', views.add_deposit.as_view(), name='add-deposit'),
    path('add-withdrawal/', views.add_withdrawal.as_view(), name='add-withdrawal'),
    path('account-opening_bal/', views.add_account_opening_bal.as_view(), name='account-opening-bal'),
    path('add-bank-charges/', views.add_bank_charges.as_view(), name='add-bank-charges'),
    path('edit-deposit/<int:pk>/', views.edit_deposit.as_view(), name='edit-deposit'),
    path('edit-withdrawal/<int:pk>/', views.edit_withdrawal.as_view(), name='edit-withdrawal'),
    path('edit-account-opening-bal/<int:pk>/', views.edit_account_opening_bal.as_view(), name='edit-account-opening-bal'),



    #path('worker-detail/<slug:slug>/',views.worker_detail, name='worker-detail'),

    #path('add-department/', views.add_department.as_view(), name='add-department'),
    #path('add-role/', views.add_role.as_view(), name='add-role'),
    #path('edit-worker/<int:pk>/', views.edit_worker.as_view(), name='edit-worker'),
    #path('delete-worker/<int:pk>/', views.delete_worker.as_view(), name='delete-worker'),



]

bjcomplexerp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('configurations/', include('configurations.urls', namespace='configurations')),
    path('task/', include('task.urls', namespace='task')),
    path('purchase/', include('purchase.urls', namespace='purchase')),
    #path('bakerycustomersinvoices/', include('bakerycustomersinvoices.urls', namespace='bakerycustomersinvoices')),
    path('bank/', include('bank.urls', namespace='bank')),
    path('bakery_accounting/', include('bakery_accounting.urls', namespace='bakery_accounting')),
    path('general_ledger/', include('general_ledger.urls', namespace='general_ledger')),
    path('procurement/', include('procurement.urls', namespace='procurement')),
    path('contact_list/', include('contact_list.urls', namespace='contact_list')),
    #path('employee/', include('employee.urls', namespace='employee')),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

purchase/urls.py
from django.urls import path
from . import views

app_name = 'purchase'

urlpatterns = [

    path('', views.purchase_invoice_client_view, name='purchases'),
    path('invoices', views.invoices_view, name='invoices'),
    path('add-purchase/', views.add_purchase.as_view(), name='add-purchase'),
    path('edit-purchase/<int:pk>/', views.edit_purchase.as_view(), name='edit-purchase'),
    #path('purchase-details/<int:pk>', views.PurchaseDetailView.as_view(), name='purchase-details'),
    path('purchase-details/<slug:slug>', views.purchase_details, name='purchase-details'),

    path('export-csv/', views.export_purchase_csv, name='export-csv'),

    path('vendors', views.vendors_view, name='vendors'),
    path('vendor-details/<slug:slug>/', views.vendor_details, name='vendor-details'),
    #path('add-vendor/', views.add_vendor.as_view(), name='add-vendor'),
    #path('edit-vendor/<int:pk>/', views.edit_vendor.as_view(), name='edit-vendor'),
    #path('invoice/<int:pk>', views.invoiceDetailView.as_view(), name='invoice-details'),

    #path('add-purchase/', views.add_purchase.as_view(), name='add-purchase'),
    #path('edit-purchase/<int:pk>/', views.edit_purchase.as_view(), name='edit-purchase'),
    #path('purchase-details/<slug:slug>/', views.purchase_details, name='purchase-details'),

    #path('suppliers/', views.products, name='suppliers'),
    #path('add-supplier/', views.add_supplier.as_view(), name='add-supplier'),
    #path('edit-supplier/<int:pk>/', views.edit_supplier.as_view(), name='edit-supplier'),

    #path('delete-opening-balance/<int:pk>/delete/', views.delete_opening_balance.as_view(), name='delete-opening-balance'),


]

purchase/models.py
from __future__ import unicode_literals
from django.db import models

from decimal import Decimal

from django.urls import reverse

from django.core.validators import RegexValidator, MinValueValidator

import uuid

import datetime
from django.utils.timezone import now
from django.template.defaultfilters import slugify

from django.db.models.signals import post_save
from configurations.models import *

from django.db.models import Sum
from django.conf import settings
from django.urls import reverse
from django.dispatch import receiver
# phone validator using regular expressions
phone_regex = RegexValidator(
    regex=r'^\+?1?\d{9,15}$',
    message='Phone number invalid. Should start with example: +237'
)



class Vendor(models.Model):

    Vendor_TYPE = (
        ('Company', 'Company'),
        ('Enterprise', 'Enterprise'),
        ('Individual', 'Individual'),
    )
    '''General information fields'''
    created = models.DateTimeField(auto_now_add=True)
    vendor_name = models.CharField(max_length=200)
    vendor_type = models.CharField(max_length=10, choices=Vendor_TYPE)
    company_name = models.CharField(max_length=200, default='')
    slug = models.SlugField(max_length=100, unique=True, blank=True)

    '''Contact details fields'''
    residential_address = models.TextField(max_length=255, null=True)
    residential_city = models.CharField(max_length=100, default='Kumba')
    residential_region = models.CharField(max_length=200, default='South West Region')
    phone = models.CharField(validators=[phone_regex], max_length=15, null=True)
    email = models.EmailField(blank=True, null=True)

    '''Bank Details'''
    bank_name1 = models.CharField(max_length=200, blank=True, null=True)
    bank_account_name1 = models.CharField(max_length=200, blank=True, null=True)
    bank_account_number1 = models.CharField(max_length = 30, blank=True, editable=True, unique=True, null=True )
    bank_name2 = models.CharField(max_length=200, blank=True, null=True)
    bank_account_name2 = models.CharField(max_length=200, blank=True, null=True)
    bank_account_number2 = models.CharField(max_length = 30, blank=True, editable=True, unique=True, null=True )


    class Meta:
        verbose_name = 'Vendor'
        verbose_name_plural = 'Vendors'

    def __str__(self):
        return self.vendor_name

    class Meta:
        verbose_name = 'vendor'
        verbose_name_plural = 'vendor'

    # def get_account_name(self):
    #     '''Make client's name the same as account name'''
    #     self.account_name = self.name
    #     return self.account_name
    def get_absolute_url(self):
        return reverse('purchase:vendor-details', args=[self.slug])

    def save(self, *args, **kwargs):
            self.slug = slugify(self.vendor_name)
            super(Vendor, self).save(*args, **kwargs)

    class Meta:
        ordering = ['-created']


class OpeningBalance(models.Model):
    created = models.DateField(default=now)
    vendor = models.ForeignKey(Vendor, null=True, on_delete=models.SET_NULL)
    amount = models.IntegerField(default=0)

    def __str__(self):
        return str(self.vendor)

    class Meta:
        ordering = ['-created']

# ---- OpeningBalance Signal ---- #
def opening_balance(sender, **kwargs):
    if kwargs['created']:
        opening_balance_trans = OpeningBalance.objects.create(vendor=kwargs['instance'])

post_save.connect(opening_balance, sender=Vendor)

# --------------- INVOICE NUMBER GENERATOR FOR Purhcases------------ #
def increment_invoice_number():
    last_invoice = Purchase.objects.all().order_by('id').last()
    today = datetime.date.today()
    today_string = today.strftime("%Y-%m-%d")

    if not last_invoice:
            return today_string + "-" + 'INV0001'

    invoice_id = last_invoice.invoice_id
    invoice_int = int(invoice_id.split('INV000')[-1])
    new_invoice_int = invoice_int + 1

    new_invoice_id = today_string + "-" + 'INV000'  + str(new_invoice_int)
    return new_invoice_id

class Purchase(models.Model):
    DEPARTMENTS = (
        ('Bakery', 'Bakery'),
        ('Boulangerie', 'Boulangerie'),
        ('Supermarket', 'Supermarket'),
        ('Bar', 'Bar'),
        ('Snack', 'Snack'),
        ('Ice Cream', 'Ice Cream'),

    )
    created = models.DateField(default=now)
    department =  models.CharField(max_length = 500, choices=DEPARTMENTS, default='', null = True, blank = True, verbose_name = 'Department')
    procurement_manager = models.CharField(max_length = 500, null = True, blank = True, verbose_name = "Procurement Manager")
    vendor = models.ForeignKey(Vendor, null=True, on_delete=models.SET_NULL)
    description = models.CharField(max_length = 500, null = True, blank = True)
    slug = models.SlugField(max_length=100, unique=True, blank=True, default=uuid.uuid4)
    invoice_id = models.CharField(max_length = 500,default=increment_invoice_number, null = True, blank = True)
    stock_dept_invoice_id = models.CharField(max_length=200, null = True, blank = True, verbose_name = "Stock Dept Invoice Id")

    amount = models.DecimalField(max_digits=20, decimal_places=2, default=0)
    vat_amount = models.DecimalField(max_digits=20, decimal_places=2, default=0)
    grand_total = models.DecimalField(max_digits=20, decimal_places=2, default=0)
    due_date = models.DateField(default=now)

    def __str__(self):
        return self.invoice_id if self.invoice_id else 'New Purchase Order'

    def get_absolute_url(self):
        return reverse('purchase:purchase-details', args=[self.slug])

    def save(self, *args, **kwargs):
            self.slug = slugify(self.vendor)
            super(Purchase, self).save(*args, **kwargs)

    class Meta:
        ordering = ['-created']

    def save(self, *args, **kwargs):
        self.title = str(self.vendor.company_name)+''+ str(self.created)
        order_items = self.order_items.all()
        self.amount = order_items.aggregate(Sum('total_price'))['total_price__sum'] if order_items.exists() else 0.00
        self.grand_total = self.amount - self.vat_amount
        #self.final_value = Decimal(self.value) - Decimal(self.discount)
        super().save(*args, **kwargs)


# ---- Order Signal ---- #
def purchase_signal(sender, **kwargs):
    if kwargs['created']:
        purchase_signal_trans = Purchase.objects.create(vendor=kwargs['instance'])

post_save.connect(purchase_signal, sender=Vendor)

class OrderItem(models.Model):
    DEPARTMENTS = (
        ('Bakery', 'Bakery'),
        ('Boulangerie', 'Boulangerie'),
        ('Supermarket', 'Supermarket'),
        ('Bar', 'Bar'),
        ('Snack', 'Snack'),
        ('Ice Cream', 'Ice Cream'),

    )
    department =  models.CharField(max_length = 500, choices=DEPARTMENTS, default='Bakery', null = True, blank = True, verbose_name = 'Department')
    purchase_order = models.ForeignKey(Purchase, on_delete=models.CASCADE, related_name='order_items')
    product = models.CharField(max_length = 500, null = True, blank = True)
    qty = models.DecimalField(max_digits=20, decimal_places=2, default=0)
    price = models.DecimalField(default=0.00, decimal_places=2, max_digits=20)
    discount_price = models.DecimalField(default=0.00, decimal_places=2, max_digits=20)
    final_price = models.DecimalField(default=0.00, decimal_places=2, max_digits=20)
    total_price = models.DecimalField(default=0.00, decimal_places=2, max_digits=20)

    def __str__(self):
        return f'{self.total_price}'
        #return f'{self.product.name}'

    def price_total_net(self):
        return ((self.qty) * (self.price))

    def save(self,  *args, **kwargs):
        #self.price = self.product.price
        #self.final_price = self.discount_price if self.discount_price > 0 else self.price
        #self.total_price = Decimal(self.qty) * Decimal(self.final_price)
        self.total_price = self.price_total_net
        super().save(*args, **kwargs)
        self.purchase_order.save()


def increment_payment_number():
    last_payment = Payment.objects.all().order_by('id').last()
    if not last_payment:
         return 'PAY0001'
    payment_id = last_payment.payment_id
    payment_int = int(payment_id.split('PAY000')[-1])
    new_payment_int = payment_int + 1
    today = datetime.date.today()
    today_string = today.strftime("%Y-%m-%d")
    new_payment_id = today_string + "-" + 'PAY000'  + str(new_payment_int)
    return new_payment_id

class Payment(models.Model):
    PAYMENTINSTALLMENTS = (
        ('1st Installment', '1st Installment'),
        ('2nd Installment', '2nd Installment'),
        ('3rd Installment', '3rd Installment'),
        ('4th Installment', '4th Installment'),
        ('5th Installment', '5th Installment'),
        ('6th Installment', '6th Installment'),
        ('7th Installment', '7th Installment'),
        ('8th Installment', '8th Installment'),
        ('9th Installment', '9th Installment'),
        ('10th Installment', '10th Installment'),
        ('11th Installment', '11th Installment'),
        ('12th Installment', '12th Installment'),
        ('13th Installment', '13th Installment'),
        ('14th Installment', '14th Installment'),
        ('15th Installment', '15th Installment'),
        ('16th Installment', '16th Installment'),
        ('17th Installment', '17th Installment'),
    )

    created = models.DateField(default=now)
    employee = models.CharField(max_length = 500, null = True, blank = True)
    #vendor= models.ForeignKey(Vendor, on_delete=models.CASCADE)
    invoice_id = models.ForeignKey(Purchase, on_delete=models.CASCADE)
    slug = models.SlugField(max_length=100, unique=True, blank=True, default=uuid.uuid4)
    installment = models.CharField(max_length=20, choices=PAYMENTINSTALLMENTS, default='1st Installment', null = True, blank = True)
    invoice_number = models.CharField(max_length = 500, null = True, blank = True)
    invoice_amount = models.IntegerField(default=0)

bakery_accounting/forms.py
from django import forms
from .models import *

class BakerySalesForm(forms.ModelForm):
    class Meta:
        model = BakerySales
        fields = "__all__"
        exclude = ('slug',)

templates/bakery_accounting/forms/add_bakery_sales.html
{% extends "base2.html" %}
{% load static %}
{% load widget_tweaks %}

{% block css %}
    <link rel="stylesheet" href="{% static '' %}bootstrap-datetimepicker.min.css">
    <link rel="stylesheet" type="text/css" href="{% static '' %}lib/pickadate.css">
 {% endblock %}

{% block title %} Add Purchase {% endblock title %}

{% block content %}

<div class="content-body">
    <!-- Basic form layout section start -->
    <section id="basic-form-layouts">
        <div class="row match-height">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title" id="basic-layout-form">Bakery Sales Form</h3>
                        <a class="heading-elements-toggle"><i class="la la-ellipsis-v font-medium-3"></i></a>
                        <div class="heading-elements">
                            <ul class="list-inline mb-0">
                                <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                                <li><a data-action="reload"><i class="ft-rotate-cw"></i></a></li>
                                <li><a data-action="expand"><i class="ft-maximize"></i></a></li>
                                <li><a data-action="close"><i class="ft-x"></i></a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="card-content collapse show">
                        <div class="card-body">
                            <div class="card-text">
                                <p></p>
                            </div>

                            <form class="form" method="post" novalidate>
                              {% csrf_token %}

                              <div class="row">
                                  <div class="col-md-3">
                                      <div class="form-group">
                                          <label for="projectinput1">Date</label>
                                          {% render_field form.created_at class="form-control" placeholder="Date" %}
                                      </div>
                                  </div>

                                  <div class="col-md-3">
                                    <div class="form-group">
                                        <label for="projectinput1">Order No</label>
                                        {% render_field form.order_no class="form-control" placeholder="" %}
                                    </div>
                                  </div>

                                  <div class="col-md-3">
                                    <div class="form-group">
                                        <label for="projectinput1">Invoice_id</label>
                                        {% render_field form.invoice_id class="form-control" placeholder="" %}
                                    </div>
                                  </div>

                                  <div class="col-md-3">
                                    <div class="form-group">
                                        <label for="projectinput1">Supplier</label>
                                        {% render_field form.supplier class="form-control" placeholder="" %}
                                    </div>
                                  </div>

                                  <div class="col-md-3">
                                    <div class="form-group">
                                        <label for="projectinput1">Customer</label>
                                        {% render_field form.customer class="form-control" placeholder="" %}
                                    </div>
                                  </div>
                              </div>

                              <div class="row">

                                <div class="col-md-3">
                                  <div class="form-group">
                                      <label for="projectinput1">Department</label>
                                      {% render_field form.department class="form-control" placeholder="" %}
                                  </div>
                                </div>

                                  <div class="col-md-3">
                                      <div class="form-group">
                                          <label for="projectinput1">Sub Department</label>
                                          {% render_field form.sub_department class="form-control" placeholder="Address" rows="2" %}
                                      </div>
                                  </div>

                                  <div class="col-md-3">
                                    <div class="form-group">
                                        <label for="projectinput1">Category</label>
                                        {% render_field form.category class="form-control" placeholder="" %}
                                    </div>
                                  </div>

                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label for="projectinput1">Session</label>
                                            {% render_field form.session class="form-control" placeholder="Address" rows="2" %}
                                        </div>
                                    </div>
                            </div>

                              <div class="row">
                                  <div class="col-md-3">
                                      <div class="form-group">
                                          <label for="projectinput1">Product</label>
                                          {% render_field form.product class="form-control" placeholder="0" %}
                                      </div>
                                  </div>

                                  <div class="col-md-3">
                                      <div class="form-group">
                                          <label for="projectinput1">Qty</label>
                                          {% render_field form.qty class="form-control" placeholder="0" %}
                                      </div>
                                  </div>

                                  <div class="col-md-3">
                                      <div class="form-group">
                                          <label for="projectinput1">Cost Price</label>
                                          {% render_field form.cost_price class="form-control" placeholder="0" %}
                                      </div>
                                  </div>



                                  <div class="col-md-3">
                                      <div class="form-group">
                                          <label for="projectinput1">Total Amount (Calculated Field)</label>
                                          {% render_field form.total_amount class="form-control" placeholder="0" %}
                                      </div>
                                  </div>
                                  <div class="col-md-3">
                                      <div class="form-group">
                                          <label for="projectinput1">Discount</label>
                                          {% render_field form.discount class="form-control" placeholder="Transaction Description" rows="2" %}
                                      </div>
                                  </div>
                              </div>


                              <div class="row">
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label for="projectinput1">Discount Value (Calculated Field)</label>
                                        {% render_field form.discount_value class="form-control" placeholder="Transaction Description" rows="2" %}
                                    </div>
                                </div>

                                  <div class="col-md-4">
                                      <div class="form-group">
                                          <label for="projectinput1">Net Amount (Calculated Field)</label>
                                          {% render_field form.net_amount class="form-control" placeholder="account debit" %}
                                      </div>
                                  </div>

                                  <div class="col-md-4">
                                      <div class="form-group">
                                          <label for="projectinput1">Commission</label>
                                          {% render_field form.commission class="form-control" placeholder="account cr" %}
                                      </div>
                                  </div>

                              </div>


                                  <div class="form-actions">
                                      <a href="{% url 'bakery_accounting:bakerysales' %}">
                                      <button type="button" class="btn btn-warning mr-1">
                                          <i class="ft-x"></i> Cancel
                                      </button>
                                    </a>
                                      <button type="submit" class="btn btn-primary">
                                          <i class="la la-check-square-o"></i> Save
                                      </button>
                                  </div>


                            </form>

                        </div>
                    </div>
                </div>
            </div>








    </section>
    <!-- // Basic form layout section end -->
</div>

{% endblock content %}
  <script src="{% static '' %}lib/picker.js"></script>
  <script src="{% static '' %}lib/picker.date.js"></script>
  <script src="{% static '' %}lib/legacy.js"></script>

  <script type="text/javascript">
      $("#id_due_date").pickadate({format: 'yyyy-mm-dd' }).val();
</script>

{% block script %}

 {% endblock %}