bank/urls.py
from django.urls import path
from . import views

app_name = 'bank'

urlpatterns = [
    path('', views.bank_view, name='bank'),
    path('bank-transactions', views.bank_transactions, name='bank-transactions'),
    path('account-detail/<slug:slug>/',views.bank_account_details, name='account-detail'),
    path('add-deposit/', views.add_deposit.as_view(), name='add-deposit'),
    path('add-withdrawal/', views.add_withdrawal.as_view(), name='add-withdrawal'),
    path('account-opening_bal/', views.add_account_opening_bal.as_view(), name='account-opening-bal'),
    path('add-bank-charges/', views.add_bank_charges.as_view(), name='add-bank-charges'),
    path('edit-deposit/<int:pk>/', views.edit_deposit.as_view(), name='edit-deposit'),
    path('edit-withdrawal/<int:pk>/', views.edit_withdrawal.as_view(), name='edit-withdrawal'),
    path('edit-account-opening-bal/<int:pk>/', views.edit_account_opening_bal.as_view(), name='edit-account-opening-bal'),



    #path('worker-detail/<slug:slug>/',views.worker_detail, name='worker-detail'),

    #path('add-department/', views.add_department.as_view(), name='add-department'),
    #path('add-role/', views.add_role.as_view(), name='add-role'),
    #path('edit-worker/<int:pk>/', views.edit_worker.as_view(), name='edit-worker'),
    #path('delete-worker/<int:pk>/', views.delete_worker.as_view(), name='delete-worker'),



]

bjcomplexerp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('configurations/', include('configurations.urls', namespace='configurations')),
    path('task/', include('task.urls', namespace='task')),
    path('purchase/', include('purchase.urls', namespace='purchase')),
    #path('bakerycustomersinvoices/', include('bakerycustomersinvoices.urls', namespace='bakerycustomersinvoices')),
    path('bank/', include('bank.urls', namespace='bank')),
    path('bakery_accounting/', include('bakery_accounting.urls', namespace='bakery_accounting')),
    path('general_ledger/', include('general_ledger.urls', namespace='general_ledger')),
    path('procurement/', include('procurement.urls', namespace='procurement')),
    path('contact_list/', include('contact_list.urls', namespace='contact_list')),
    #path('employee/', include('employee.urls', namespace='employee')),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

general_ledger/urls.py
from django.urls import path
from . import views

app_name = 'general_ledger'

urlpatterns = [
    path('', views.general_ledger_view, name='general-ledger'),
    path('transaction-detail/<slug:slug>/',views.transaction_details, name='transaction-details'),
    path('add-transaction/', views.add_general_ledger_trans.as_view(), name='add-transaction'),
    path('edit-transaction/<int:pk>/', views.edit_general_ledger_trans.as_view(), name='edit-transaction'),
]

task/urls.py
from django.urls import path
from . import views

app_name = 'task'

urlpatterns = [
    path('', views.task_home, name='task-home'),
    path('add-task/', views.add_task.as_view(), name='add-task'),
    path('task-detail/<slug:slug>/',views.task_detail, name='task-detail'),
    path('edit-task/<int:pk>/', views.edit_task.as_view(), name='edit-task'),

]

purchase/models.py
from __future__ import unicode_literals
from django.db import models

from decimal import Decimal

from django.urls import reverse

from django.core.validators import RegexValidator, MinValueValidator

import uuid

import datetime
from django.utils.timezone import now
from django.template.defaultfilters import slugify

from django.db.models.signals import post_save
from configurations.models import *

from django.db.models import Sum
from django.conf import settings
from django.urls import reverse
from django.dispatch import receiver
# phone validator using regular expressions
phone_regex = RegexValidator(
    regex=r'^\+?1?\d{9,15}$',
    message='Phone number invalid. Should start with example: +237'
)



class Vendor(models.Model):

    Vendor_TYPE = (
        ('Company', 'Company'),
        ('Enterprise', 'Enterprise'),
        ('Individual', 'Individual'),
    )
    '''General information fields'''
    created = models.DateTimeField(auto_now_add=True)
    vendor_name = models.CharField(max_length=200)
    vendor_type = models.CharField(max_length=10, choices=Vendor_TYPE)
    company_name = models.CharField(max_length=200, default='')
    slug = models.SlugField(max_length=100, unique=True, blank=True)

    '''Contact details fields'''
    residential_address = models.TextField(max_length=255, null=True)
    residential_city = models.CharField(max_length=100, default='Kumba')
    residential_region = models.CharField(max_length=200, default='South West Region')
    phone = models.CharField(validators=[phone_regex], max_length=15, null=True)
    email = models.EmailField(blank=True, null=True)

    '''Bank Details'''
    bank_name1 = models.CharField(max_length=200, blank=True, null=True)
    bank_account_name1 = models.CharField(max_length=200, blank=True, null=True)
    bank_account_number1 = models.CharField(max_length = 30, blank=True, editable=True, unique=True, null=True )
    bank_name2 = models.CharField(max_length=200, blank=True, null=True)
    bank_account_name2 = models.CharField(max_length=200, blank=True, null=True)
    bank_account_number2 = models.CharField(max_length = 30, blank=True, editable=True, unique=True, null=True )


    class Meta:
        verbose_name = 'Vendor'
        verbose_name_plural = 'Vendors'

    def __str__(self):
        return self.vendor_name

    class Meta:
        verbose_name = 'vendor'
        verbose_name_plural = 'vendor'

    # def get_account_name(self):
    #     '''Make client's name the same as account name'''
    #     self.account_name = self.name
    #     return self.account_name
    def get_absolute_url(self):
        return reverse('purchase:vendor-details', args=[self.slug])

    def save(self, *args, **kwargs):
            self.slug = slugify(self.vendor_name)
            super(Vendor, self).save(*args, **kwargs)

    class Meta:
        ordering = ['-created']


class OpeningBalance(models.Model):
    created = models.DateField(default=now)
    vendor = models.ForeignKey(Vendor, null=True, on_delete=models.SET_NULL)
    amount = models.IntegerField(default=0)

    def __str__(self):
        return str(self.vendor)

    class Meta:
        ordering = ['-created']

# ---- OpeningBalance Signal ---- #
def opening_balance(sender, **kwargs):
    if kwargs['created']:
        opening_balance_trans = OpeningBalance.objects.create(vendor=kwargs['instance'])

post_save.connect(opening_balance, sender=Vendor)

# --------------- INVOICE NUMBER GENERATOR FOR Purhcases------------ #
def increment_invoice_number():
    last_invoice = Purchase.objects.all().order_by('id').last()
    today = datetime.date.today()
    today_string = today.strftime("%Y-%m-%d")

    if not last_invoice:
            return today_string + "-" + 'INV0001'

    invoice_id = last_invoice.invoice_id
    invoice_int = int(invoice_id.split('INV000')[-1])
    new_invoice_int = invoice_int + 1

    new_invoice_id = today_string + "-" + 'INV000'  + str(new_invoice_int)
    return new_invoice_id

class Purchase(models.Model):
    DEPARTMENTS = (
        ('Bakery', 'Bakery'),
        ('Boulangerie', 'Boulangerie'),
        ('Supermarket', 'Supermarket'),
        ('Bar', 'Bar'),
        ('Snack', 'Snack'),
        ('Ice Cream', 'Ice Cream'),

    )
    created = models.DateField(default=now)
    department =  models.CharField(max_length = 500, choices=DEPARTMENTS, default='', null = True, blank = True, verbose_name = 'Department')
    procurement_manager = models.CharField(max_length = 500, null = True, blank = True, verbose_name = "Procurement Manager")
    vendor = models.ForeignKey(Vendor, null=True, on_delete=models.SET_NULL)
    description = models.CharField(max_length = 500, null = True, blank = True)
    slug = models.SlugField(max_length=100, unique=True, blank=True, default=uuid.uuid4)
    invoice_id = models.CharField(max_length = 500,default=increment_invoice_number, null = True, blank = True)
    stock_dept_invoice_id = models.CharField(max_length=200, null = True, blank = True, verbose_name = "Stock Dept Invoice Id")

    amount = models.DecimalField(max_digits=20, decimal_places=2, default=0)
    vat_amount = models.DecimalField(max_digits=20, decimal_places=2, default=0)
    grand_total = models.DecimalField(max_digits=20, decimal_places=2, default=0)
    due_date = models.DateField(default=now)

    def __str__(self):
        return self.invoice_id if self.invoice_id else 'New Purchase Order'

    def get_absolute_url(self):
        return reverse('purchase:purchase-details', args=[self.slug])

    def save(self, *args, **kwargs):
            self.slug = slugify(self.vendor)
            super(Purchase, self).save(*args, **kwargs)

    class Meta:
        ordering = ['-created']

    def save(self, *args, **kwargs):
        self.title = str(self.vendor.company_name)+''+ str(self.created)
        order_items = self.order_items.all()
        self.amount = order_items.aggregate(Sum('total_price'))['total_price__sum'] if order_items.exists() else 0.00
        self.grand_total = self.amount - self.vat_amount
        #self.final_value = Decimal(self.value) - Decimal(self.discount)
        super().save(*args, **kwargs)


# ---- Order Signal ---- #
def purchase_signal(sender, **kwargs):
    if kwargs['created']:
        purchase_signal_trans = Purchase.objects.create(vendor=kwargs['instance'])

post_save.connect(purchase_signal, sender=Vendor)

class OrderItem(models.Model):
    DEPARTMENTS = (
        ('Bakery', 'Bakery'),
        ('Boulangerie', 'Boulangerie'),
        ('Supermarket', 'Supermarket'),
        ('Bar', 'Bar'),
        ('Snack', 'Snack'),
        ('Ice Cream', 'Ice Cream'),

    )
    department =  models.CharField(max_length = 500, choices=DEPARTMENTS, default='Bakery', null = True, blank = True, verbose_name = 'Department')
    purchase_order = models.ForeignKey(Purchase, on_delete=models.CASCADE, related_name='order_items')
    product = models.CharField(max_length = 500, null = True, blank = True)
    qty = models.DecimalField(max_digits=20, decimal_places=2, default=0)
    price = models.DecimalField(default=0.00, decimal_places=2, max_digits=20)
    discount_price = models.DecimalField(default=0.00, decimal_places=2, max_digits=20)
    final_price = models.DecimalField(default=0.00, decimal_places=2, max_digits=20)
    total_price = models.DecimalField(default=0.00, decimal_places=2, max_digits=20)

    def __str__(self):
        return f'{self.total_price}'
        #return f'{self.product.name}'

    def price_total_net(self):
        return ((self.qty) * (self.price))

    def save(self,  *args, **kwargs):
        #self.price = self.product.price
        #self.final_price = self.discount_price if self.discount_price > 0 else self.price
        #self.total_price = Decimal(self.qty) * Decimal(self.final_price)
        self.total_price = self.price_total_net
        super().save(*args, **kwargs)
        self.purchase_order.save()


def increment_payment_number():
    last_payment = Payment.objects.all().order_by('id').last()
    if not last_payment:
         return 'PAY0001'
    payment_id = last_payment.payment_id
    payment_int = int(payment_id.split('PAY000')[-1])
    new_payment_int = payment_int + 1
    today = datetime.date.today()
    today_string = today.strftime("%Y-%m-%d")
    new_payment_id = today_string + "-" + 'PAY000'  + str(new_payment_int)
    return new_payment_id

class Payment(models.Model):
    PAYMENTINSTALLMENTS = (
        ('1st Installment', '1st Installment'),
        ('2nd Installment', '2nd Installment'),
        ('3rd Installment', '3rd Installment'),
        ('4th Installment', '4th Installment'),
        ('5th Installment', '5th Installment'),
        ('6th Installment', '6th Installment'),
        ('7th Installment', '7th Installment'),
        ('8th Installment', '8th Installment'),
        ('9th Installment', '9th Installment'),
        ('10th Installment', '10th Installment'),
        ('11th Installment', '11th Installment'),
        ('12th Installment', '12th Installment'),
        ('13th Installment', '13th Installment'),
        ('14th Installment', '14th Installment'),
        ('15th Installment', '15th Installment'),
        ('16th Installment', '16th Installment'),
        ('17th Installment', '17th Installment'),
    )

    created = models.DateField(default=now)
    employee = models.CharField(max_length = 500, null = True, blank = True)
    #vendor= models.ForeignKey(Vendor, on_delete=models.CASCADE)
    invoice_id = models.ForeignKey(Purchase, on_delete=models.CASCADE)
    slug = models.SlugField(max_length=100, unique=True, blank=True, default=uuid.uuid4)
    installment = models.CharField(max_length=20, choices=PAYMENTINSTALLMENTS, default='1st Installment', null = True, blank = True)
    invoice_number = models.CharField(max_length = 500, null = True, blank = True)
    invoice_amount = models.IntegerField(default=0)

general_ledger/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, DetailView, DeleteView, UpdateView, CreateView, View
from django.urls import reverse_lazy
from django.contrib import messages
from django.core.paginator import Paginator

from django.db.models import Sum
from django.db.models import Q, F, When, Case
from django.db.models import Count

from django.core.paginator import Paginator
from django.contrib.auth.models import User
import datetime

from django.http import HttpResponse, JsonResponse
import csv
import xlwt
import pandas as pd
import io


from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from . models import *

# Create your views here.
#----------------------------- Bakery Sales View ----------------------#
def general_ledger_view(request):
    start_date = request.GET.get('start_date')
    end_date = request.GET.get('end_date')

    transactions = Expenses.objects.all()


    #if start_date and end_date:
        #customer =  list(Expenses.objects.filter(created_at__range=[start_date, end_date]).aggregate(total=Count('invoice_id')).values())[0]
        #total_bakerysales = list(bakerysales.filter(created_at__range=[start_date, end_date]).aggregate(Sum('total_amount')).values())[0]
        #bakerysales = bakerysales.filter(created_at__range=[start_date, end_date])
        #boulangerie_sales = list(bakerysales.filter(sub_department__exact='Boulangerie').aggregate(Sum('total_amount')).values())[0]
        #patisserie_sales = list(bakerysales.filter(sub_department__exact='Patisserie').aggregate(Sum('total_amount')).values())[0]

    #else:
        #customer =  list(Expenses.objects.aggregate(total=Count('invoice_id')).values())[0]
        #total_bakerysales = list(bakerysales.aggregate(Sum('total_amount')).values())[0]
        #bakerysales = bakerysales
        #boulangerie_sales = list(bakerysales.filter(sub_department__exact='Boulangerie').aggregate(Sum('total_amount')).values())[0]
        #patisserie_sales = list(bakerysales.filter(sub_department__exact='Patisserie').aggregate(Sum('total_amount')).values())[0]


    template_name = 'general_ledger/general_ledger.html'
    context = { 'transactions':transactions,


                }
    return render(request, template_name, context)
#----------------------------- Bakery Sales View Ends----------------------#

def transaction_details(request, slug):
    trans = get_object_or_404(Expenses, slug=slug)
    #products = Product.objects.all()

    template_name = 'general_ledger/transaction_details.html'
    context = {'trans':trans}
    return render(request, template_name, context)

#----------------------------- Bakery Add SalesView  and Edit View ----------------------#
class add_general_ledger_trans(SuccessMessageMixin, CreateView):
    model = Expenses
    template_name = 'general_ledger/forms/add_gl_transaction.html'
    fields = '__all__'
    exclude = ('slug',)
    success_url = reverse_lazy('general_ledger:general-ledger')
    success_message = 'Transaction Successfully Added !!!'

class edit_general_ledger_trans(SuccessMessageMixin, UpdateView):
    model = Expenses
    template_name = 'general_ledger/forms/edit_gl_transaction.html'
    fields = '__all__'
    exclude = ('slug',)
    success_url = reverse_lazy('general_ledger:general-ledger')
    success_message = 'Transaction Successfully Edited !!!'

#----------------------------- Bakery Add SalesView  and Edit View Ends----------------------#

#

templates/general_ledger/transaction_details.html
{% extends "base2.html" %}
{% load static %}
{% load widget_tweaks %}

{% block css %}
    <link rel="stylesheet" href="{% static '' %}bootstrap-datetimepicker.min.css">
    <link rel="stylesheet" type="text/css" href="{% static '' %}lib/pickadate.css">
 {% endblock %}

{% block title %} Transaction Details{% endblock title %}

{% block content %}

<div class="content-body">
  <div class="content-overlay"></div>
  <div class="content-wrapper">
      <div class="content-header row">
          <div class="content-header-left col-md-6 col-12 mb-2 breadcrumb-new">
              <h3 class="content-header-title mb-0 d-inline-block">Transaction Details</h3>
              <div class="row breadcrumbs-top d-inline-block">
                  <div class="breadcrumb-wrapper col-12">
                      <ol class="breadcrumb">
                          <li class="breadcrumb-item"><a href="{% url 'task:task-home' %}">Home</a>
                          </li>
                          <li class="breadcrumb-item"><a href="#">Transaction</a>
                          </li>
                          <li class="breadcrumb-item active">Transaction Details
                          </li>
                      </ol>
                  </div>
              </div>
          </div>
          <div class="content-header-right col-md-6 col-12">
              <div class="btn-group float-md-right">
                  <button class="btn btn-info dropdown-toggle mb-1" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Action</button>
                  <div class="dropdown-menu arrow">
                    <a class="dropdown-item" href=""><i class="la la-edit mr-1"></i> Edit</a>

                      <div class="dropdown-divider"></div><a class="dropdown-item" href="#"><i class="fa fa-cog mr-1"></i> Settings</a>
                  </div>
              </div>
          </div>
      </div>
      <div class="content-body">
          <section class="card">
              <div id="invoice-template" class="card-body p-4">
                  <!-- Invoice Company Details -->
                  <div id="invoice-company-details" class="row">


                  </div>
                  <!-- Invoice Company Details -->

                  <!-- Invoice Customer Details -->
                  <div id="invoice-customer-details" class="row pt-2">
                      <div class="col-12 text-center text-sm-left">
                          <p class="text-muted"> <h3>Task Title : {{ trans.description|slice:":25"}} ...</h3> </p>
                      </div>
                      <div class="col-sm-6 col-12 text-center text-sm-left">
                          <ul class="px-0 list-unstyled">
                              <li class="text-bold-800 text-uppercase"> Department | {{ trans.department }}  </li>
                              <li class="text-bold-800">  Employee / Management | {{ trans.employee_management }}  </li>
                              <li> Date Created | {{ trans.created_at }} </li>
                            <!--  <li>Albuquerque,</li>
                              <li>New Mexico-87102.</li> -->
                          </ul>
                      </div>
                      <div class="col-sm-6 col-12 text-center text-sm-right">
                          <p class="text-uppercase"><span class="text-muted">Transaction Id :</span> {{ trans.transaction_id }}</p>
                          <p><span class="text-muted">Employee :</span> {{ trans.employee }}</p>
                          <p><span class="text-muted">Institution :</span> {{ trans.institution  }}</p>
                      </div>
                  </div>
                  <!-- Invoice Customer Details -->

                  <!-- Invoice Items Details -->
                  <div id="invoice-items-details" class="pt-2">
                      <div class="row">
                          <div class="table-responsive col-12">
                              <table class="table">
                                  <thead>
                                      <tr>
                                          <th>Description</th>
                                          <th>Amount</th>
                                          <th>Account Dr</th>
                                          <th>Account Cr</th>
                                      </tr>
                                  </thead>
                                  <tbody>
                                      <tr>
                                          <td class="phone">{{trans.description}}</td>
                                          <td class="phone">{{trans.amount|floatformat:0 }}</td>
                                          <td class="phone">{{trans.accounts_dr}}</td>
                                          <td class="phone">{{trans.accounts_cr}}</td>

                                      </tr>

                                  </tbody>
                              </table>
                          </div>
                      </div>
                  </div>

              </div>
          </section>

      </div>
  </div>

</div>

{% endblock content %}
  <script src="{% static '' %}lib/picker.js"></script>
  <script src="{% static '' %}lib/picker.date.js"></script>
  <script src="{% static '' %}lib/legacy.js"></script>

  <script type="text/javascript">
      $("#id_due_date").pickadate({format: 'yyyy-mm-dd' }).val();
</script>

{% block script %}

 {% endblock %}